apiVersion: apps/v1
kind: Deployment
metadata:
  name: 31-07-frontend
spec:
  selector:
    matchLabels:
      deployment-name: 31-07-frontend
  replicas: 2
  template:
    metadata:
      labels:
        deployment-name: 31-07-frontend 
    spec:
      containers:
        - name: application-frontend-container
          image: iurib8it148.azurecr.io/buildingtesting:945d09a9bcf61f3b487ad91daf40e8cfea85a6fd
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: 31-07-cluster-service
  name: cluster-service-31-07
spec:
  type: ClusterIP
  ports:
  - name: cluster-service-port-31-07
    port: 80
    protocol: TCP
  selector:
    deployment-name: 31-07-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: 31-07-cluster-service 
  name: cluster-service-loadbalancer-31-07
spec:
  type: LoadBalancer
  ports:
  - name: load-balancer-service-port-31-07
    port: 80
    protocol: TCP
  selector:
    deployment-name: 31-07-frontend