apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-frontend
spec:
  selector:
    matchLabels:
      deployment-name: application-frontend
  replicas: 2
  template:
    metadata:
      labels:
        deployment-name: application-frontend 
    spec:
      containers:
        - name: application-frontend-container
          image: iurib8it148.azurecr.io/buildingtesting:945d09a9bcf61f3b487ad91daf40e8cfea85a6fd
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: frontend-cluster-service
  name: frontend-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: frontend-cluster-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: application-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-loadbalancer
  labels:
    app: frontend-service-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: application-frontend
