apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-02-08-deployment
spec:
  selector:
    matchLabels:
      deployment-name: frontend-02-08-deployment
  replicas: 2
  template:
    metadata:
      labels:
        deployment-name: frontend-02-08-deployment 
    spec:
      containers:
        - name: frontend-container-02-08
          image: iuri89/frontend-image-02-08:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: service-label-cluster-service-02-08
  name: frontend-cluster-service-02-08
spec:
  type: ClusterIP
  ports:
  - name: ionic-cluster-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: ionic-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: service-label-cluster-service-02-08 
  name: frontend-loadbalancer-02-08
spec:
  type: LoadBalancer
  ports:
  - name: load-balancer-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: frontend-02-08-deployment